" auto indent
filetype plugin indent on

" enable syntax highlighting
syntax on

" tabwidth
set tabstop=4
set shiftwidth=4

" line numbers
set number

" themes
colorscheme elflord

" gvim layout
set guioptions-=r
set guioptions-=L
set guioptions-=m
set guioptions-=T
